# Generated by Django 4.0.6 on 2022-07-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='NIC',
        ),
    ]
