# Generated by Django 4.0.6 on 2022-07-31 08:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_remove_lecturer_title_remove_student_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='LK'),
        ),
    ]
