# Generated by Django 4.0.6 on 2022-07-31 08:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_lecturer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
