# Generated by Django 4.0.6 on 2022-07-31 08:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_lecturer_title_alter_lecturer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
