# Generated by Django 4.0.6 on 2022-08-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_session_class_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='class_material',
        ),
    ]
