# Generated by Django 4.0.6 on 2022-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_remove_session_class_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='class_material',
            field=models.FileField(blank=True, null=True, upload_to='material/'),
        ),
    ]
