# Generated by Django 4.0.6 on 2022-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_session_class_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='file_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
